import { Injectable } from '@angular/core';
import { Image } from './models/images.module';
import { delay, Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class ImageService {
  private images: Image[] = [
    {
      id: 1,
      src: '01_img.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },
    {
      id: 1,
      src: 'funny-1.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },
    {
      id: 2,
      src: '02_img.jpg',
      name: 'Sea',
      loacation: 'Swiss',
      year: 2021,
      price: 1000,
    },
    {
      id: 1,
      src: 'funny-3.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },
    {
      id: 3,
      src: '03_img.jpg',
      name: 'Red Wood',
      loacation: 'Romania',
      year: 2022,
      price: 4000,
    },
    {
      id: 4,
      src: '04_img.jpg',
      name: 'Turtle',
      loacation: 'Austria',
      year: 2001,
      price: 3400,
    },
    {
      id: 1,
      src: 'funny-4.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },

    {
      id: 4,
      src: '05_img.jpg',
      name: 'mountain see',
      loacation: 'Bosnia',
      year: 2011,
      price: 2000,
    },
    {
      id: 1,
      src: 'funny-5.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },
    {
      id: 5,
      src: '06_img.jpg',
      name: 'Vineyard',
      loacation: 'Hungery',
      year: 2003,
      price: 1000,
    },
    {
      id: 1,
      src: 'funny-6.jpg',
      name: 'Bear',
      loacation: 'Alaska',
      year: 2004,
      price: 2000,
    },
    {
      id: 6,
      src: '07_img.jpg',
      name: 'Zebras',
      loacation: 'Africa',
      year: 2024,
      price: 5000,
    },
    {
      id: 7,
      src: '08_img.jpg',
      name: 'Giraffe',
      loacation: 'Africa',
      year: 1990,
      price: 12000,
    },
    {
      id: 8,
      src: '09_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '09_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '09_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '10_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '11_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '12img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '13_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '14_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '15_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '16_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '17_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '18_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '19_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '20_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '21_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '22_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '23_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '24_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: '25_img.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: 'funny-1.jpg',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
    {
      id: 8,
      src: 'funny-2.webp',
      name: 'Another Image',
      loacation: 'Africa',
      year: 2006,
      price: 2000,
    },
  ];

  getImages(): Observable<Image[]> {
    return of(this.images).pipe(delay(500));
  }
}
